version: '3.8'

services:
    whisper-api:
        build: .
        container_name: whisper-api
        ports:
            - '5000:5000'
        environment:
            - CUDA_VISIBLE_DEVICES=0
        volumes:
            - ./logs:/app/logs
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: ['gpu']
